<?php

########################################################################
# Extension Manager/Repository config file for ext: "jobcenter"
#
# Auto generated by Extension Builder 2013-06-05
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Jobcenter',
	'description' => 'Jobcenter',
	'category' => 'plugin',
	'author' => 'Stefan Froemken',
	'author_email' => 'projects@jweiland.net',
	'author_company' => 'jweiland.net',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);